//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureWaveInterForm.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CultureWaveInterForm.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string buttonLogIn {
            get {
                return ResourceManager.GetString("buttonLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EVENTOS PROGRAMADOS.
        /// </summary>
        internal static string labelActiveEvents {
            get {
                return ResourceManager.GetString("labelActiveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible.
        /// </summary>
        internal static string labelAvailable {
            get {
                return ResourceManager.GetString("labelAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad.
        /// </summary>
        internal static string labelCapacity {
            get {
                return ResourceManager.GetString("labelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción evento.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha evento.
        /// </summary>
        internal static string labelEventDate {
            get {
                return ResourceManager.GetString("labelEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        internal static string labelEvents {
            get {
                return ResourceManager.GetString("labelEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string labelExit {
            get {
                return ResourceManager.GetString("labelExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sillas fijas.
        /// </summary>
        internal static string labelFixedSeats {
            get {
                return ResourceManager.GetString("labelFixedSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string labelLogOut {
            get {
                return ResourceManager.GetString("labelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre evento.
        /// </summary>
        internal static string labelNameEvents {
            get {
                return ResourceManager.GetString("labelNameEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre espacio.
        /// </summary>
        internal static string labelNameSpace {
            get {
                return ResourceManager.GetString("labelNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario.
        /// </summary>
        internal static string labelNameUser {
            get {
                return ResourceManager.GetString("labelNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESERVAS.
        /// </summary>
        internal static string labelRecentReservations {
            get {
                return ResourceManager.GetString("labelRecentReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservas.
        /// </summary>
        internal static string labelReserves {
            get {
                return ResourceManager.GetString("labelReserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asientos.
        /// </summary>
        internal static string labelSeats {
            get {
                return ResourceManager.GetString("labelSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacios.
        /// </summary>
        internal static string labelSpace {
            get {
                return ResourceManager.GetString("labelSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacios.
        /// </summary>
        internal static string labelSpaces {
            get {
                return ResourceManager.GetString("labelSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        internal static string labelTicket {
            get {
                return ResourceManager.GetString("labelTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string labelUsers {
            get {
                return ResourceManager.GetString("labelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string roundedButtonAccept {
            get {
                return ResourceManager.GetString("roundedButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string roundedButtonCancel {
            get {
                return ResourceManager.GetString("roundedButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Ticket.
        /// </summary>
        internal static string roundedButtonCloseTicket {
            get {
                return ResourceManager.GetString("roundedButtonCloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string roundedButtonCreate {
            get {
                return ResourceManager.GetString("roundedButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear evento.
        /// </summary>
        internal static string roundedButtonCreateEvent {
            get {
                return ResourceManager.GetString("roundedButtonCreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string roundedButtonDelete {
            get {
                return ResourceManager.GetString("roundedButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Reserva.
        /// </summary>
        internal static string roundedButtonDeleteReserve {
            get {
                return ResourceManager.GetString("roundedButtonDeleteReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string roundedButtonEdit {
            get {
                return ResourceManager.GetString("roundedButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string roundedButtonExit {
            get {
                return ResourceManager.GetString("roundedButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar con IA.
        /// </summary>
        internal static string roundedButtonGenerateIA {
            get {
                return ResourceManager.GetString("roundedButtonGenerateIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string roundedButtonLogOut {
            get {
                return ResourceManager.GetString("roundedButtonLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reservar.
        /// </summary>
        internal static string roundedButtonReserve {
            get {
                return ResourceManager.GetString("roundedButtonReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string roundedButtonReset {
            get {
                return ResourceManager.GetString("roundedButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string roundedButtonSearch {
            get {
                return ResourceManager.GetString("roundedButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string roundedRadioButtonYesAvailable {
            get {
                return ResourceManager.GetString("roundedRadioButtonYesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string roundedRadioButtonYesSeats {
            get {
                return ResourceManager.GetString("roundedRadioButtonYesSeats", resourceCulture);
            }
        }
    }
}
