//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CultureWaveInterForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cultureWaveEntities1 : DbContext
    {
        public cultureWaveEntities1()
            : base("name=cultureWaveEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eventTable> eventTable { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<reserve> reserve { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<seat> seat { get; set; }
        public virtual DbSet<space> space { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
